SkillCert/skillcert-frontend

package-lock.json
src/app/home/components/aboutUsPage.tsx
src/app/settings/profileSettings/myProfileSetting.tsx

#32 #38 
This PR implements two key UI components for the SkillCert platform with a consistent modern dark theme design. The update includes a comprehensive user profile form for personal information management and an informative About section that introduces users to the platform's blockchain-based certificate innovations.
- ✅ Created responsive `ProfileForm` component for user profile management
- ✅ Implemented `AboutSkillCert` component showcasing platform overview
- ✅ Established consistent dark theme with unified color scheme (#9333EA purple, #111827 background)
- ✅ Built modular, reusable component architecture
- ✅ Added comprehensive form state management using React hooks
- ✅ Implemented responsive layouts for mobile and desktop viewports
- **User Data Management**: Name, …

feat: built the profile settings and the about us page

---

package-lock.json
src/app/page.tsx
src/components/learnMoreButton.tsx

Create Learn More Button
Issue
Create Learn More button component as described in the issue.
Description
Implemented a LearnMoreButton component in src/components/learnMoreButton.tsx.
The button follows the style and layout provided in the Figma design reference.
It is responsive and accessible, using semantic HTML and Tailwind CSS.
References
Design reference: https://www.figma.com/design/haKZnxXmooo5vnV8TVr7zz/Skillcert-Design?node-id=35-26&t=CDb1nCPXzz3K3I7h-0
Visual guidance: 
Notes
No additional files were created.
All code is contained strictly within the specified file.
#8

feat: Create Learn More Button

---

component.
package-lock.json
src/app/home/page.tsx
src/app/page.tsx
src/app/register/userRegister.tsx
src/app/settings/components/sidebarSettings.tsx
src/app/settings/passwordSettings/ myPasswordSetting.tsx
src/app/settings/passwordSettings/page.tsx
src/components/ChangePasswordForm.tsx

closes: #18 
Implemented a comprehensive password settings page with a dedicated form component for users to change their passwords securely.
- **`ChangePasswordForm.tsx`** - Reusable password change form component with:
- Current password input
- New password input  
- Password confirmation input
-   submission handling
- **Responsive Design**: Mobile-first approach with breakpoints for desktop
- **Dark Theme**: Consistent with application's dark theme using `#111827` background
- **Purple Accent**: Brand-consistent purple (`#9333EA`) for highlights and borders
- **Form Validation**: Controlled inputs with proper state management
- **Accessibility**: Proper form labels and semantic HTML structure
- Clean, centered layout with proper spacing
- Rounded input fields with consistent styling …

Create Password Settings Page

---

package-lock.json
package.json
src/app/coursesPage/coursesPreview/components/resumeModal.tsx
src/app/page.tsx

The resume modal has been created successfully.
close[#54]

Created the resume modal

---

src/app/coursesPage/coursesPreview/headerModal.tsx

Closes #53 
Implements the preview modal header component as specified in Figma design.
- ✅ **HeaderModal Component**: Complete header with course information and navigation
- ✅ **Typography**: Exact Figma specifications using Poppins font
- Course Name: 40px, weight 500
- Course Description: 24px, weight 400
- ✅ **Navigation Tabs**: Resume, Content, Teacher, Reviews
- Dimensions: 176x50px with 25px border radius
- Selected state: #A855F7 background, white text
- Unselected state: transparent background, #9333EA text
- ✅ **Divider Line**: Purple (#C084FC) with 0.2° rotation
- ✅ **Interactive Elements**: 
- Tab switching functionality
- Close button (X) with hover effects
- Responsive design
- ✅ Matches Figma specifications exactly
- ✅ Proper color scheme and spacing
- ✅ Responsive layout …

feat: Create preview modal header component

---

src/app/coursesPreview/components/teacherModal.tsx

feat: add teacher preview modal component
- Implements the teacher preview modal in app/coursesPreview/components/teacherModal.tsx
- Adheres to design references (Figma)
- Does not include a header section per spec
Closes #56

add teacher preview modal

---

src/app/home/components/welcomepage/courseExplorationSection.tsx
src/app/home/page.tsx

Implemented the explore Course section according to the Figma without changing any other files.
closes #69

Feat: Implemented the home exploreCourses page

---

src/app/home/mainPage.tsx

This PR implements the main page dashboard UI according to the Figma design, featuring action buttons and a progress panel.
- **Added:** Main page dashboard component (`src/app/home/mainPage.tsx`)
- **Features:**
- Welcome section with prominent title
- Two action buttons: "My learning" and "Course Catalog"
- Progress panel with metrics (Certificates, Enrolled Courses, Learning Hours)
- Responsive layout with dark theme
- Proper spacing and typography hierarchy
- **Layout:** Horizontal arrangement with action buttons on left, progress panel on right
- **Buttons:** Square format (160px × 160px) with large icons
- **Panel:** Rectangular format that extends to the left
- **Theme:** Dark theme with gray-900 backgrounds and white text
- **Icons:** Large, prominent icons (96px × 96px) using …

feat: implement main page dashboard UI with action buttons and progress

---

src/app/coursesPage/studentCourses.tsx
src/app/instructor/courses/[id]/page.tsx
src/app/instructor/courses/instructorCoursesView.tsx

feat: issue files

---

babel.config.js
src/app/instructor/courses/components/courseCard.tsx
src/app/instructor/courses/instructorCoursesView.tsx
src/app/instructor/courses/page.tsx
src/app/instructor/page.tsx
src/lib/interface.ts

close #133 
- What feature or bug does this address?    
- i created the instructor courses page and linked both the overview and courses page together wiht a navigation button below thw navbar   
- i deleted the babel.config to make the project run on my local machine
- 
---  

created the instructor coureses

---

package-lock.json
package.json
src/app/coursesPage/components/createCourse.tsx
src/app/coursesPage/courseExplore.tsx
src/contract_connections/CourseRegistry/createCourse.ts

This PR implements complete smart contract integration for the Create
Course feature using Soroban SDK and Freighter wallet 
- What feature or bug does this address? 
- ✅ **Smart Contract Integration**: Full integration of
`course_registry_create_course` function from CourseRegistry contract
- ✅ **Reusable React Hook**: `useCreateCourse()` hook for component
reusability across the application
- ✅ **Complete UI Implementation**: Modal-based course creation form
with comprehensive validation
- ✅ **Production-Ready Error Handling**: Graceful handling of
wallet, network, and contract errors
- ✅ **TypeScript Type Safety**: Full type definitions and interfaces
throughout the integration
- ✅ **Environment Configuration**: Proper environment variable setup
for contract address and network …

feat: implement smart contract integration for Create Course feature

---

src/components/helloTest.tsx

Implemented a frontend feature that calls the hello_world() function from the smart contract and displays the result on the ui
---  

feat: web3 integration

---

src/contract_connections/CourseRegistry/addModule.ts

This PR introduces a new `addModule.ts` file that provides a robust TypeScript implementation for adding modules to courses in the Skillcert platform. This feature enables instructors to dynamically expand their course content by adding new modules with proper validation and error handling.
- **New Feature**: Module creation functionality with comprehensive input validation
- **Enhanced User Experience**: Clean React hooks integration for seamless UI integration
- **Data Integrity**: Input sanitization and validation to prevent invalid module creation
- **Scalability**: Follows established contract patterns for consistent module ID generation
- **Contract Integration Ready**: The current implementation uses simulated contract calls - ready for actual blockchain integration
- **Validation …

feat: new integration addModule

---

pnpm-lock.yaml
src/app/instructor/courses/[courseId]/components/courseModules.tsx
src/app/instructor/courses/[courseId]/page.tsx

Closes #145 
Created a comprehensive Course Modules component as requested in `app/instructor/courses/[id]/components/courseModules.tsx` following the provided Figma design specifications.
**Core Functionality:**
- ✅ **Drag & Drop Reordering** - Fully functional module reordering with visual feedback
- ✅ **Responsive Design** - Three-tier responsive system (mobile/tablet/desktop)
- ✅ **Module Management** - Edit and Delete actions for each module
- ✅ **Add Module** - Purple gradient "Add Module" button in header
**Design & UX:**
- ✅ **Gradient Number Badges** - Purple gradient circular badges (purple-500 to purple-700)
- ✅ **Dark Theme** - purple dark background matching Figma specifications
- ✅ **Typography Hierarchy** - Clean title, lesson count with BookOpen icon, and descriptions
- ✅ …

feat: course-modules-component

---

docs/save_profile_react_integration.md
package.json
pnpm-lock.yaml
src/app/contract_connections/UserProfile/useSaveProfile.tsx
src/app/layout.tsx
src/app/register/page.tsx
src/app/register/teacherRegister.tsx
src/components/ui/form.tsx
src/hooks/use-save-profile.ts

**Closes #143**
This PR implements a complete React integration for the `save_profile` function from the user_management Soroban smart contract, along with form improvements using modern React patterns.
- ✅ Created custom React hook for Stellar blockchain integration
- ✅ Implements Freighter wallet connection and transaction signing
- ✅ Handles complete contract interaction lifecycle
- ✅ Provides comprehensive state management (loading, error, success, transaction hash)
- ✅ Uses environment variables for configuration (not hardcoded addresses)
- ✅ Includes proper TypeScript interfaces and error handling
- ✅ Converts form data to Soroban ScVal format for contract compatibility
- ✅ Migrated from basic useState to React Hook Form with Zod validation
- ✅ Implemented shadcn/ui Form components …

feat: build-connection-for-save-profile-information-feature

---

src/app/globals.css

Clean Up Default Styles
https://github.com/SkillCert/skillcert-frontend/issues/172
- What feature or bug does this address? 
- Remove default CSS styles from globals.css that are not used in the actual design.      
---  

Clean Up Default Styles

---

src/app/contract_connections/UserProfile/saveProfile.tsx
src/app/contract_connections/UserProfile/useSaveProfile.tsx

- What feature or bug does this address?       
---  

fix: remove comments

---

src/app/about/components/heroSection.tsx
src/app/about/page.tsx

close #214 
- What feature or bug does this address?   
- I added the hero section of the about page    
---  

added hero section

---

src/app/myCoursesPage/components/enrolledCourseCard.tsx
src/app/myCoursesPage/coursesRegistered.tsx
src/app/myCoursesPage/myCoursesPage.tsx
src/app/myCoursesPage/page.tsx

Removed unnecessary comments from the `app/myCoursesPage/` section.  
This PR cleans up the code by deleting comments, improving readability and maintainability.  
N/A (no UI changes).  
- No functional changes were introduced.  
- No new dependencies or migrations added.
---  

chore(myCoursesPage): remove comments.

---

src/app/coursesPreview/components/teacherModal.tsx

- What feature or bug does this address?       
---  

remove comments from coursesPreview section

---

package-lock.json
src/app/globals.css
src/app/layout.tsx

- Optimized Fonts  
Add screenshots or screen recordings that visually demonstrate the changes.

Fixed optimised fonts

---

UI_GUIDELINES.md

This PR adds a `UI_GUIDELINES.md` file to define consistent naming, styling, and component rules for the frontend
* Addresses the need for consistent UI development and maintainable components.
* Provides rules for file/folder naming, component naming, props, styling, and general best practices
Not applicable (documentation only)
* Focused on frontend conventions and reusable component practices
* No new dependencies introduced
---

Add UI guidelines document

---

.gitignore
bun.lock
src/app/home/page.tsx
src/app/layout.tsx
src/app/not-found.tsx

- Added a new NotFound component for handling 404 errors with a user-friendly message and navigation link.
- Commented out the PrinciplesSection import in home/page.tsx for future reference.
#175 
Creater a not-found screen to handle mis-typed(non existing) route,
added a not-found.tsx in the app root
- What feature or bug does this address?       
---  

- Introduced a new bun.lock file to manage dependencies.

---

src/app/home/page.tsx
src/hooks/healthCheckCourseAccess.ts
src/hooks/healthCheckCourseRegistry.ts

Closes #212 
This pull request introduces health check functions for the Soroban smart contracts used in the SkillCert platform. The health check mechanism ensures that each contract is responsive before proceeding with further execution, improving reliability and error handling.
- **Added health check functions for each contract:**
- `healthCheckCourseAccess` in `src/hooks/healthCheckCourseAccess.ts`
- `healthCheckCourseRegistry` in `src/hooks/healthCheckCourseRegistry.ts`
- Each function calls the respective contract's `health_check` method and expects a response of `'hello'`. If the response is not received, execution is aborted and an error is thrown.
- Improved error handling for missing environment variables and unexpected contract responses.
Call the health check function before …

Health check

---

listCourseAccess.test.ts

Remove comments on test
- What feature or bug does this address?       
- This promote the clean up of code removing unuse comments
---  

remove comments on test

---

src/app/home/components/welcomepage/ready.tsx
src/app/home/page.tsx

Made the Ready component responsive across all screens (mobile, tablet desktop) and improved the overall layout of all properties with in the file.
Location: src/app/home/components/welcomepage/ready.tsx
closes #249
---
- Added proper responsive padding
- Improved button layout and scaling across breakpoints
- Enhanced text readability with better spacing and font sizes
- Applied mobile-first design principles
- Used Tailwind's responsive classes consistently
- Maintained existing color scheme and gradient
- Ensured accessibility with proper contrast ratios
- Fixed button width constraints for better mobile experience
Tested across multiple viewport sizes:
- Mobile (320px - 640px)
- Tablet (641px - 1024px)
- Desktop (1025px+)

Fix: Full Responsive (Ready)
